import test from 'node:test';
import {createHash} from 'node:crypto';
import {fs,path,assert,ctl,ROOT,json} from './helpers.js';
const hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const machinePath=/(?:\/(?:home|Users)\/[^/\s"'`<>]+|\b[A-Za-z]:[\\/](?![\\/]))/;
test('machine path assertion detects generic home and drive paths without rejecting project paths',()=>{
 for(const value of ['/home/test-user/project','/Users/test-user/project','C:\\Users\\test-user\\project','D:/work/project'])assert.match(value,machinePath);
 for(const value of ['.specify/scripts/bash/check-prerequisites.sh','/.specify/scripts/bash/setup-plan.sh','https://github.com/github/spec-kit','scripts/import-upstreams.js'])assert.doesNotMatch(value,machinePath);
});
test('generated artifacts and upstream import scripts contain no machine paths',()=>{
 for(const directory of ['generated/github-spec-kit','scripts'])for(const [name,p] of ctl.files(path.join(ROOT,directory))){
  // The package includes native JS scripts, not local legacy bytecode caches.
  if(directory==='scripts'&&!name.endsWith('.js'))continue;
  assert.doesNotMatch(fs.readFileSync(p,'utf8'),machinePath,`${directory}/${name}`);
 }
});
const entries=[...ctl.validateCatalog(json(path.join(ROOT,'catalog.json'))).values()];
test('complete catalog retains 54 upstream, four originals and twelve local curations with kind counts',()=>{assert.equal(entries.length,70);const upstream=entries.filter(i=>!['original','local-hermes-curation'].includes(i.provenance.source)),original=entries.filter(i=>i.provenance.source==='original'),curated=entries.filter(i=>i.provenance.source==='local-hermes-curation');assert.equal(upstream.length,54);assert.equal(curated.length,12);assert.deepEqual(original.map(i=>i.id).sort(),['claude-reviewer','cursor-reviewer','example-bundle','verify-before-reporting']);assert.deepEqual(Object.fromEntries(['skill','agent','plugin'].map(k=>[k,entries.filter(i=>i.kind===k).length])),{skill:67,agent:2,plugin:1});for(const item of upstream){const p=path.join(ROOT,item.path);assert.ok(fs.statSync(path.join(p,'SKILL.md')).isFile());assert.ok(fs.statSync(path.join(p,'LICENSE')).isFile());assert.match(item.provenance.revision,/^[a-f0-9]{40}$/);assert.match(item.provenance.review_scope,/not a security audit/);ctl.digest(p);}const matt=entries.filter(i=>i.id.startsWith('mattpocock-'));assert.equal(matt.length,38);assert.equal(matt.filter(i=>i.provenance.maturity==='stable').length,27);assert.equal(matt.filter(i=>i.provenance.maturity==='optional').length,4);assert.equal(matt.filter(i=>i.provenance.maturity==='experimental').length,7);assert.deepEqual(matt.find(i=>i.id==='mattpocock-git-guardrails-claude-code').harnesses,['claude']);});
for(const [vendor,count]of [['mattpocock-skills',159],['github-spec-kit',833]])test(`upstream ${vendor} preserves all ${count} original file hashes`,()=>{const root=path.join(ROOT,'vendor',vendor),manifest=json(path.join(root,'IMPORT-PROVENANCE.json'));assert.equal(Object.keys(manifest.upstream_sha256).length,count);for(const [name,wanted]of Object.entries(manifest.upstream_sha256))assert.equal(hash(path.join(root,name)),wanted,name);assert.ok(!ctl.files(root).some(([name])=>path.basename(name)==='AGENTS.md'));});
test('Matt resources and OpenAI metadata resolve retained links',()=>{for(const item of entries.filter(i=>i.id.startsWith('mattpocock-'))){const p=path.join(ROOT,item.path);assert.ok(fs.statSync(path.join(p,'agents/openai.yaml')).isFile());const body=fs.readFileSync(path.join(p,'SKILL.md'),'utf8');for(const [,link]of body.matchAll(/\]\(([^)]+)\)/g))if(/\.(md|sh|cjs)$/.test(link)&&!link.includes('://')&&!link.startsWith('./src/'))assert.ok(fs.statSync(path.join(p,link)).isFile(),`${item.id}: ${link}`);}});
test('official generated skills preserve hashes frontmatter rendered scripts and no machine paths',()=>{const root=path.join(ROOT,'generated/github-spec-kit'),manifest=json(path.join(root,'GENERATION.json'));assert.equal(Object.keys(manifest.generated_sha256).length,10);const skills=fs.readdirSync(path.join(root,'generic')).filter(n=>fs.existsSync(path.join(root,'generic',n,'SKILL.md')));assert.equal(skills.length,10);for(const name of skills){const p=path.join(root,'generic',name,'SKILL.md'),body=fs.readFileSync(p,'utf8');assert.equal(hash(p),manifest.generated_sha256[name+'/SKILL.md']);assert.match(body,new RegExp('^name: "?'+name+'"?$','m'));assert.doesNotMatch(body,/__SPECKIT_[A-Z_]+__|\{SCRIPT\}|\{ARGS\}|\{AGENT\}/);for(const [,script]of body.matchAll(/\.specify\/scripts\/bash\/([\w-]+\.sh)/g))assert.ok(fs.statSync(path.join(ROOT,'vendor/github-spec-kit/scripts/bash',script)).isFile());assert.doesNotMatch(body,machinePath);}});
