import test from 'node:test';
import {fs,path,assert,ctl,ROOT,temp,json,writeJSON,cli} from './helpers.js';
import { mergeLocalExamples } from '../scripts/import-upstreams.js';
test('invalid local identifiers reject on reimport',t=>{const p=temp(t);writeJSON(path.join(p,'local-examples.json'),[{id:'../escape'}]);assert.throws(()=>mergeLocalExamples([],p));});
test('duplicate local ids and upstream conflicts reject on reimport',t=>{const p=temp(t),item=json(path.join(ROOT,'local-examples.json'))[0];for(const [locals,upstream]of [[[item,item],[]],[[item],[item]]]){writeJSON(path.join(p,'local-examples.json'),locals);assert.throws(()=>mergeLocalExamples(upstream,p),/duplicate catalog id/);}});
test('reimport preserves optional sidecar without mutating upstreams',()=>{const upstream=json(path.join(ROOT,'catalog.json')).items.filter(i=>i.provenance.source!=='original'),before=JSON.stringify(upstream),local=json(path.join(ROOT,'local-examples.json'));assert.deepEqual(mergeLocalExamples(upstream,ROOT),[...upstream,...local]);assert.deepEqual(mergeLocalExamples(upstream,ROOT),[...upstream,...local]);assert.equal(JSON.stringify(upstream),before);assert.equal(mergeLocalExamples(upstream,ROOT).length,52);});
const local=json(path.join(ROOT,'local-examples.json')),catalog=ctl.validateCatalog(json(path.join(ROOT,'catalog.json')));
function example(id,kind,p,h){const item=catalog.get(id);assert.ok(item);assert.equal(item.kind,kind);assert.equal(item.path,p);assert.deepEqual(item.harnesses,h);assert.ok(fs.existsSync(path.join(ROOT,p)));assert.deepEqual(Object.fromEntries(['source','revision','license','reviewed','maturity'].map(k=>[k,item.provenance[k]])),{source:'original',revision:'v1',license:'All rights reserved',reviewed:true,maturity:'optional'});assert.match(item.provenance.review_scope,/not a security audit/);return item;}
test('original plugin is explicitly inert README-only fixture',()=>{const item=example('example-bundle','plugin','plugins/example-bundle',['hermes','claude','codex','cursor']);const body=fs.readFileSync(path.join(ROOT,item.path,'README.md'),'utf8');for(const token of ['INERT','not a runnable plugin','hooks'])assert.ok(body.includes(token));assert.deepEqual(fs.readdirSync(path.join(ROOT,item.path)),['README.md']);});
for(const h of ['cursor','claude'])test(`${h} native reviewer retains explicit frontmatter and cautious instructions`,()=>{const item=example(h+'-reviewer','agent','agents/'+h+'/reviewer.md',[h]);assert.equal(item.name,'reviewer.md');const body=fs.readFileSync(path.join(ROOT,item.path),'utf8');assert.ok(body.startsWith('---\nname: reviewer\ndescription:'));for(const token of ['read-only','exact paths','unverified'])assert.ok(body.includes(token));if(h==='claude')assert.match(body.split('---')[1],/tools: Read, Glob, Grep/);else assert.doesNotMatch(body.split('---')[1],/tools:/);});
test('portable verification skill preserves evidence requirements',()=>{const item=example('verify-before-reporting','skill','skills/verify-before-reporting',['hermes','claude','codex','cursor']);const body=fs.readFileSync(path.join(ROOT,item.path,'SKILL.md'),'utf8');assert.ok(body.startsWith('---\nname: verify-before-reporting\n'));for(const token of ['description: Use when reporting completion. Require observable evidence.','acceptance','Never fabricate','read back'])assert.ok(body.includes(token));});
function fixture(t){const base=temp(t),repo=path.join(base,'repo');fs.mkdirSync(repo);writeJSON(path.join(repo,'catalog.json'),{version:1,items:local});for(const item of local){const dest=path.join(repo,item.path);fs.mkdirSync(path.dirname(dest),{recursive:true});ctl.copyPayload(path.join(ROOT,item.path),dest);}return {base,repo,run(h,ids,targets,apply=false){const env=path.join(base,'env.json');writeJSON(env,{harness:h,items:ids,targets});return cli(['sync','--repo',repo,'--env',env,...(apply?['--apply']:[])],{cwd:base});}};}
test('optional payloads preview apply and read back unchanged across four harnesses',t=>{const f=fixture(t);for(const h of ['hermes','claude','codex','cursor']){const home=path.join(f.base,h),targets={skill:path.join(home,'.agents/skills'),plugin:path.join(home,'staged/plugins')},ids=['verify-before-reporting','example-bundle'];if(['claude','cursor'].includes(h)){targets.agent=path.join(home,'.agents/agents');ids.push(h+'-reviewer');}let r=f.run(h,ids,targets);assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,ids.map(i=>'install '+i+'\n').join(''));assert.ok(!fs.existsSync(home));r=f.run(h,ids,targets,true);assert.equal(r.status,0,r.stderr);for(const item of local.filter(i=>ids.includes(i.id))){const dest=path.join(targets[item.kind],item.name),wanted=ctl.digest(path.join(f.repo,item.path));assert.equal(ctl.digest(dest),wanted);assert.deepEqual(json(path.join(targets[item.kind],'.agents-managed',item.name+'.json')),{id:item.id,digest:wanted});}r=f.run(h,ids,targets,true);assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,ids.map(i=>'unchanged '+i+'\n').join(''));}});
test('foreign native agent rejects before any target writes',t=>{const f=fixture(t);for(const [h,foreign]of [['claude','cursor-reviewer'],['cursor','claude-reviewer'],['hermes','claude-reviewer'],['codex','cursor-reviewer']]){const r=f.run(h,['verify-before-reporting',foreign],{skill:path.join(f.base,h,'skills'),agent:path.join(f.base,h,'agents')},true);assert.equal(r.status,2);assert.match(r.stderr,/incompatible harness/);assert.equal(r.stdout,'');assert.ok(!fs.existsSync(path.join(f.base,h)));}});
test('optional plugin sentinel script staged never executed',t=>{const f=fixture(t),sentinel=path.join(f.base,'executed'),source=path.join(f.repo,'plugins/example-bundle/install.sh');fs.writeFileSync(source,`#!/bin/sh\ntouch ${sentinel}\n`,{mode:0o755});const target=path.join(f.base,'staged'),r=f.run('codex',['example-bundle'],{plugin:target},true);assert.equal(r.status,0,r.stderr);assert.deepEqual(fs.readFileSync(source),fs.readFileSync(path.join(target,'example-bundle/install.sh')));assert.ok(!fs.existsSync(sentinel));});
