import test from 'node:test';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {fs,path,assert,ctl,ROOT,temp,json} from './helpers.js';
function run(command,args,opts={}){const r=spawnSync(command,args,{encoding:'utf8',maxBuffer:8*1024*1024,...opts});assert.equal(r.status,0,`${command} ${args.join(' ')}\n${r.stderr}\n${r.stdout}`);return r;}
test('npm tarball retains catalog resources all vendor manifests and executable npx with isolated HOME/cache',t=>{
 const p=temp(t),pack=JSON.parse(run('npm',['pack','--ignore-scripts','--json','--pack-destination',p],{cwd:ROOT}).stdout)[0],tar=path.join(p,pack.filename),unpack=path.join(p,'unpack');fs.mkdirSync(unpack);run('tar',['-xzf',tar,'-C',unpack]);const repo=path.join(unpack,'package'),pkg=json(path.join(repo,'package.json'));
 assert.equal(pkg.name,'@rauleinstein/agents');assert.equal(pkg.type,'module');assert.equal(pkg.engines.node,'>=20');assert.deepEqual(pkg.bin,{agentsctl:'bin/agentsctl.js'});assert.ok((fs.statSync(path.join(repo,'bin/agentsctl.js')).mode&0o111)!==0);for(const k of ['preinstall','install','postinstall','prepare'])assert.ok(!pkg.scripts?.[k]);assert.ok(!pkg.dependencies&&!pkg.devDependencies);assert.ok(!fs.existsSync(path.join(repo,'agentsctl.py')));
 for(const vendor of ['mattpocock-skills','github-spec-kit','ponytail']){assert.deepEqual(fs.readFileSync(path.join(repo,'vendor',vendor,'IMPORT-PROVENANCE.json')),fs.readFileSync(path.join(ROOT,'vendor',vendor,'IMPORT-PROVENANCE.json')));const manifest=json(path.join(repo,'vendor',vendor,'IMPORT-PROVENANCE.json'));for(const [name,digest]of Object.entries(manifest.upstream_sha256))assert.equal(createHash('sha256').update(fs.readFileSync(path.join(repo,'vendor',vendor,name))).digest('hex'),digest,name);}
 for(const item of json(path.join(ROOT,'catalog.json')).items)assert.equal(ctl.digest(path.join(repo,item.path)),ctl.digest(path.join(ROOT,item.path)),item.id);
 const home=path.join(p,'home'),cwd=path.join(p,'elsewhere'),cache=path.join(p,'npm-cache');fs.mkdirSync(home);fs.mkdirSync(cwd);const options={cwd,env:{...process.env,HOME:home,npm_config_cache:cache,npm_config_ignore_scripts:'true'}};
 const npx=args=>run('npx',['--offline','--yes','--ignore-scripts','--cache',cache,'--package='+tar,'agentsctl',...args],options);
 assert.equal(npx(['--version']).stdout,'0.1.0\n');assert.match(npx(['--help']).stdout,/--harness/);const preview=npx(['sync','--harness','cursor']).stdout;assert.equal(preview.trim().split('\n').length,37);assert.ok(preview.trim().split('\n').every(l=>l.startsWith('install ')));assert.ok(!fs.existsSync(path.join(home,'.agents')));assert.equal(npx(['sync','--harness','cursor','--apply']).stdout,preview);const repeated=npx(['sync','--harness','codex','--apply']).stdout;assert.ok(repeated.trim().split('\n').every(l=>l.startsWith('unchanged ')));const env=json(path.join(repo,'environments/cursor.json')),catalog=ctl.validateCatalog(json(path.join(repo,'catalog.json')));for(const id of env.items){const item=catalog.get(id),dest=path.join(home,'.agents/skills',item.name);assert.equal(ctl.digest(dest),ctl.digest(path.join(repo,item.path)),id);assert.deepEqual(json(path.join(home,'.agents/skills/.agents-managed',item.name+'.json')),{id,digest:ctl.digest(dest)});}
 const result=spawnSync('npx',['--offline','--yes','--ignore-scripts','--cache',cache,'--package='+tar,'agentsctl','sync','--harness','cursor','--env','missing'],{encoding:'utf8',...options});assert.equal(result.status,2);assert.match(result.stderr,/select exactly one/);
});
