import test from 'node:test';
import {fs,path,assert,ctl,ROOT,temp,fixture,cli,json,addPlugin} from './helpers.js';
import {spawnSync} from 'node:child_process';
const cases=[
 ['catalog version',(c,e)=>c.version=true],['catalog list',c=>c.items={}],['duplicate catalog',c=>c.items.push(structuredClone(c.items[0]))],
 ['bad id',c=>c.items[0].id='../bad'],['bad name',c=>c.items[0].name='UPPER'],['reserved name',c=>c.items[0].name='.agents-managed'],
 ['path traversal',c=>c.items[0].path='skills/../skills/sample'],['absolute source',c=>c.items[0].path='/etc/passwd'],['unreviewed',c=>c.items[0].provenance.reviewed=false],['no revision',c=>delete c.items[0].provenance.revision],
 ['bad harnesses',c=>c.items[0].harnesses='hermes'],['duplicate harnesses',c=>c.items[0].harnesses=['hermes','hermes']],['incompatible',c=>c.items[0].harnesses=['claude']],['bad kind',c=>c.items[0].kind='other'],
 ['unknown harness',(c,e)=>e.harness='other'],['empty selection',(c,e)=>e.items=[]],['duplicate selection',(c,e)=>e.items=['sample','sample']],['unknown selection',(c,e)=>e.items=['missing']],
 ['relative target',(c,e)=>e.targets.skill='relative'],['noncanonical target',(c,e)=>e.targets.skill+='/../target'],['overlap repo',(c,e,f)=>e.targets.skill=path.join(f.repo,'output')],['ancestor repo',(c,e,f)=>e.targets.skill=f.base],
 ['overlap roots',(c,e)=>e.targets.plugin=path.join(e.targets.skill,'plugins')],['same roots',(c,e)=>e.targets.plugin=e.targets.skill],['bad target map',(c,e)=>e.targets=[]],['unknown target kind',(c,e)=>e.targets.other=e.targets.skill],
 ['null catalog', (c,e,f)=>f.catalog=null],['missing targets',(c,e)=>e.targets={}],['null environment',(c,e,f)=>f.environment=null],
 ['missing skill definition',(c,e,f)=>fs.unlinkSync(path.join(f.source,'SKILL.md'))],['nul source',c=>c.items[0].path+='\0'],['nul target',(c,e)=>e.targets.skill+='\0']
];
for(const [label,mutate]of cases)test(`schema ${label} rejects before writes`,t=>{const f=fixture(t);mutate(f.catalog,f.environment,f);f.save();assert.throws(()=>f.sync(true),ctl.SafetyError);assert.ok(!fs.existsSync(f.target));});
test('absolute paths strip trailing separators but preserve filesystem root',()=>{
 const root=path.parse(ROOT).root,example=path.join(root,'example');
 assert.equal(ctl.absolute(example+path.sep),example);
 assert.equal(ctl.absolute(root),root);
 assert.equal(ctl.absolute(root+path.sep),root);
 assert.throws(()=>ctl.absolute(example+path.sep+'..'+path.sep+'target'),ctl.SafetyError);
});
test('overlap is symmetric for trailing separators and filesystem roots',()=>{
 const root=path.parse(ROOT).root,ancestor=path.join(root,'example'),child=path.join(ancestor,'child');
 for(const [a,b,wanted] of [[ancestor+path.sep,child,true],[ancestor,child+path.sep,true],[ancestor+path.sep,ancestor,true],[root,child,true],[root+path.sep,child,true],[ancestor,path.join(root,'example-other'),false]]){
  assert.equal(ctl.overlap(a,b),wanted,`${a} vs ${b}`);
  assert.equal(ctl.overlap(b,a),wanted,`${b} vs ${a}`);
 }
});
test('trailing separator repository ancestor rejects before writes',t=>{
 const f=fixture(t);f.environment.targets.skill=f.base+path.sep;f.save();
 assert.throws(()=>f.sync(true),/target overlaps repository/);
 assert.ok(!fs.existsSync(f.target));assert.ok(!fs.existsSync(path.join(f.base,'sample')));
 assert.deepEqual(fs.readdirSync(f.base).sort(),['env.json','repo']);
});
test('trailing separator skill root rejects nested declared plugin root before writes',t=>{
 const f=fixture(t);f.environment.targets.skill+=path.sep;f.environment.targets.plugin=path.join(f.target,'plugins');f.save();
 assert.throws(()=>f.sync(true),/target roots overlap/);
 assert.ok(!fs.existsSync(f.target));
});
test('nested plugin under trailing skill root preserves installed ownership without writes',t=>{
 const f=fixture(t);assert.deepEqual(f.sync(true),['install sample']);
 const original=structuredClone(f.environment),metadata=path.join(f.target,'.agents-managed/sample.json');
 const metadataBefore=fs.readFileSync(metadata),treeBefore=ctl.digest(f.target);
 addPlugin(f);f.environment.targets.skill+=path.sep;f.environment.targets.plugin=path.join(f.target,'sample');f.save();
 let writes=false;
 assert.throws(()=>f.sync(true,{afterPreflight(){writes=true;}}),/target roots overlap/);
 assert.equal(writes,false);assert.equal(ctl.digest(f.target),treeBefore);
 assert.deepEqual(fs.readFileSync(metadata),metadataBefore);
 assert.deepEqual(json(metadata),{id:'sample',digest:ctl.digest(f.source)});
 f.environment=original;f.save();assert.deepEqual(f.sync(),['unchanged sample']);
});
test('duplicate destinations reject all before writes',t=>{const f=fixture(t);const item=structuredClone(f.catalog.items[0]);item.id='second';f.catalog.items.push(item);f.environment.items.push('second');f.save();assert.throws(()=>f.sync(true),/duplicate destination/);assert.ok(!fs.existsSync(f.target));});
test('invalid native agent and plugin shapes reject',t=>{const f=fixture(t);f.catalog.items[0].kind='agent';f.environment.targets={agent:f.target};f.save();assert.throws(()=>f.sync(true),ctl.SafetyError);f.catalog.items[0].kind='plugin';f.catalog.items[0].path='skills/sample/SKILL.md';f.environment.targets={plugin:f.target};f.save();assert.throws(()=>f.sync(true),ctl.SafetyError);assert.ok(!fs.existsSync(f.target));});
test('unmanaged destination is preserved',t=>{const f=fixture(t);fs.mkdirSync(path.join(f.target,'sample'),{recursive:true});fs.writeFileSync(path.join(f.target,'sample/mine'),'mine');assert.throws(()=>f.sync(true),/unmanaged destination/);assert.equal(fs.readFileSync(path.join(f.target,'sample/mine'),'utf8'),'mine');});
test('local edits preserved',t=>{const f=fixture(t);f.sync(true);const p=path.join(f.target,'sample/SKILL.md');fs.writeFileSync(p,'local');assert.throws(()=>f.sync(true),/local modifications/);assert.equal(fs.readFileSync(p,'utf8'),'local');});
test('missing managed payload rejects',t=>{const f=fixture(t);f.sync(true);ctl.remove(path.join(f.target,'sample'));assert.throws(()=>f.sync(true),/managed payload missing/);});
test('malformed and mismatched metadata rejects',t=>{const f=fixture(t);f.sync(true);const meta=path.join(f.target,'.agents-managed/sample.json');for(const v of ['{','[]','{}',JSON.stringify({id:'other',digest:ctl.digest(f.source)}),JSON.stringify({id:'sample',digest:'wrong'}),JSON.stringify({id:'sample',digest:'a'.repeat(64),extra:true})]){fs.writeFileSync(meta,v);assert.throws(()=>f.sync(true),ctl.SafetyError);}fs.unlinkSync(meta);fs.mkdirSync(meta);assert.throws(()=>f.sync(true),ctl.SafetyError);});
for(const where of ['source ancestor','source payload','target ancestor','metadata','metadata ancestor','destination payload','unused target'])test(`${where} symlink rejects`,t=>{const f=fixture(t);switch(where){case 'source ancestor':fs.renameSync(path.dirname(f.source),path.join(f.repo,'real'));fs.symlinkSync(path.join(f.repo,'real'),path.dirname(f.source));break;case 'source payload':fs.symlinkSync(path.join(f.source,'SKILL.md'),path.join(f.source,'link'));break;case 'target ancestor':fs.mkdirSync(path.join(f.base,'real'));fs.symlinkSync(path.join(f.base,'real'),f.target);break;case 'unused target':f.environment.targets.plugin=path.join(f.base,'unused');fs.symlinkSync(path.join(f.base,'missing'),f.environment.targets.plugin);f.save();break;default:f.sync(true);if(where==='destination payload'){const p=path.join(f.target,'sample/SKILL.md');fs.unlinkSync(p);fs.symlinkSync(path.join(f.source,'SKILL.md'),p);}else if(where==='metadata'){const p=path.join(f.target,'.agents-managed/sample.json');fs.renameSync(p,path.join(f.base,'meta'));fs.symlinkSync(path.join(f.base,'meta'),p);}else{const p=path.join(f.target,'.agents-managed');fs.renameSync(p,path.join(f.base,'metas'));fs.symlinkSync(path.join(f.base,'metas'),p);}}
 assert.throws(()=>f.sync(true),/symlink/);});
test('special payload file rejected before read',t=>{const f=fixture(t);const r=spawnSync('mkfifo',[path.join(f.source,'fifo')]);assert.equal(r.status,0);assert.throws(()=>f.sync(true),/not a regular/);assert.ok(!fs.existsSync(f.target));});
test('all item preflight prevents partial writes',t=>{const f=fixture(t);f.catalog.items.push({...structuredClone(f.catalog.items[0]),id:'second',name:'second',path:'missing'});f.environment.items.push('second');f.save();assert.throws(()=>f.sync(true));assert.ok(!fs.existsSync(f.target));});
test('existing lock rejects apply not preview',t=>{const f=fixture(t),lock=path.join(f.target,'.agents-sync.lock');fs.mkdirSync(lock,{recursive:true});fs.writeFileSync(path.join(lock,'owner'),'other');assert.deepEqual(f.sync(),['install sample']);assert.throws(()=>f.sync(true),/target locked/);assert.equal(fs.readFileSync(path.join(lock,'owner'),'utf8'),'other');assert.ok(!fs.existsSync(path.join(f.target,'sample')));});
test('multiple roots release acquired locks on failure',t=>{const f=fixture(t),other=addPlugin(f);fs.mkdirSync(path.join(other,'.agents-sync.lock'),{recursive:true});assert.throws(()=>f.sync(true),/target locked/);assert.ok(!fs.existsSync(path.join(f.target,'.agents-sync.lock')));assert.ok(fs.existsSync(path.join(other,'.agents-sync.lock')));});
test('all roots including unused locked in sorted order and re-preflight rejects late destination',t=>{const f=fixture(t),other=addPlugin(f),unused=path.join(f.base,'unused');f.environment.targets.agent=unused;f.save();let seen=false;assert.throws(()=>f.sync(true,{afterLocks(first){seen=true;assert.deepEqual(first.roots,[f.target,unused,other].sort());for(const r of first.roots)assert.ok(fs.statSync(path.join(r,'.agents-sync.lock')).isDirectory());fs.mkdirSync(path.join(f.target,'sample'));fs.writeFileSync(path.join(f.target,'sample/mine'),'late');}}),/unmanaged/);assert.ok(seen);assert.equal(fs.readFileSync(path.join(f.target,'sample/mine'),'utf8'),'late');for(const r of [f.target,unused,other])assert.ok(!fs.existsSync(path.join(r,'.agents-sync.lock')));});
test('unused declared target locked',t=>{const f=fixture(t);f.environment.targets.plugin=path.join(f.base,'unused');f.save();fs.mkdirSync(path.join(f.base,'unused/.agents-sync.lock'),{recursive:true});assert.throws(()=>f.sync(true),/target locked/);assert.ok(!fs.existsSync(path.join(f.target,'sample')));});
for(const boundary of ['metadata','payload'])test(`${boundary} replacement failure rolls back update`,t=>{const f=fixture(t);f.sync(true);const meta=path.join(f.target,'.agents-managed/sample.json'),before=fs.readFileSync(meta);fs.writeFileSync(path.join(f.source,'SKILL.md'),'new');assert.throws(()=>f.sync(true,{rename(src,dst){if((boundary==='metadata'&&dst===meta)||(boundary==='payload'&&path.basename(src).startsWith('.agents-stage-')))throw new Error('injected swap');fs.renameSync(src,dst);}}),/injected/);assert.equal(fs.readFileSync(path.join(f.target,'sample/SKILL.md'),'utf8'),'# sample');assert.deepEqual(fs.readFileSync(meta),before);assert.deepEqual(fs.readdirSync(f.target).sort(),['.agents-managed','sample']);});
test('install metadata failure removes new payload and locks',t=>{const f=fixture(t);const other=addPlugin(f);assert.throws(()=>f.sync(true,{rename(src,dst){if(dst.endsWith('.json'))throw new Error('injected');fs.renameSync(src,dst);}}),/injected/);assert.ok(!fs.existsSync(path.join(f.target,'sample')));assert.ok(!fs.existsSync(path.join(f.target,'.agents-managed/sample.json')));for(const root of [f.target,other])assert.ok(!fs.existsSync(path.join(root,'.agents-sync.lock')));});
for(const partial of [false,true])test(`postcommit backup cleanup failure partial=${partial} warns successful`,t=>{const f=fixture(t);f.sync(true);fs.writeFileSync(path.join(f.source,'SKILL.md'),'new');const warnings=[],backups=[];assert.deepEqual(f.sync(true,{remove(p){if(path.basename(p).startsWith('.agents-backup-')){backups.push(p);if(partial)fs.unlinkSync(path.join(p,'SKILL.md'));throw new Error('injected cleanup');}ctl.remove(p);},warn:m=>warnings.push(m)}),['update sample']);assert.equal(backups.length,1);assert.match(warnings[0],/warning:.*committed.*injected cleanup.*manual cleanup/);assert.ok(warnings[0].includes(backups[0]));assert.ok(fs.existsSync(backups[0]));assert.equal(fs.existsSync(path.join(backups[0],'SKILL.md')),!partial);assert.equal(fs.readFileSync(path.join(f.target,'sample/SKILL.md'),'utf8'),'new');assert.deepEqual(f.sync(),['unchanged sample']);assert.deepEqual(json(path.join(f.target,'.agents-managed/sample.json')),{id:'sample',digest:ctl.digest(f.source)});});
for(const mutation of ['destination','metadata','source before copy','source after copy','source symlink after copy'])test(`late ${mutation} rejects without overwriting edits`,t=>{const f=fixture(t);f.sync(true);fs.writeFileSync(path.join(f.source,'SKILL.md'),'new');const payload=path.join(f.target,'sample/SKILL.md'),meta=path.join(f.target,'.agents-managed/sample.json');assert.throws(()=>f.sync(true,{copy(src,dst){if(mutation==='source before copy')fs.writeFileSync(path.join(src,'SKILL.md'),'late source');ctl.copyPayload(src,dst);if(mutation==='destination')fs.writeFileSync(payload,'late local');if(mutation==='metadata')fs.writeFileSync(meta,'local metadata');if(mutation==='source after copy')fs.writeFileSync(path.join(src,'SKILL.md'),'late source');if(mutation==='source symlink after copy'){fs.unlinkSync(path.join(src,'SKILL.md'));fs.symlinkSync(payload,path.join(src,'SKILL.md'));}}}),ctl.SafetyError);assert.equal(fs.readFileSync(payload,'utf8'),mutation==='destination'?'late local':'# sample');if(mutation==='metadata')assert.equal(fs.readFileSync(meta,'utf8'),'local metadata');assert.ok(!fs.existsSync(path.join(f.target,'.agents-sync.lock')));});
for(const mutation of ['destination','source'])test(`unchanged ${mutation} rechecked under locks`,t=>{const f=fixture(t);f.sync(true);assert.throws(()=>f.sync(true,{afterPreflight(){fs.writeFileSync(path.join(mutation==='source'?f.source:path.join(f.target,'sample'),'SKILL.md'),'late unchanged');}}),ctl.SafetyError);});
test('configuration changes while acquiring locks reject',t=>{const f=fixture(t);assert.throws(()=>f.sync(true,{afterLocks(){fs.writeFileSync(path.join(f.source,'SKILL.md'),'changed');}}),/changed during lock/);assert.ok(!fs.existsSync(path.join(f.target,'sample')));});
test('replacement lock is not removed',t=>{const f=fixture(t),lock=path.join(f.target,'.agents-sync.lock');f.sync(true,{replace(plan,options){fs.renameSync(lock,path.join(f.base,'old-lock'));fs.mkdirSync(lock);fs.writeFileSync(path.join(lock,'owner'),'other');ctl.replaceArtifact(plan,options);}});assert.equal(fs.readFileSync(path.join(lock,'owner'),'utf8'),'other');});
test('write failure releases multiple locks',t=>{const f=fixture(t),other=addPlugin(f);assert.throws(()=>f.sync(true,{replace(){throw new Error('injected');}}),/injected/);for(const root of [f.target,other])assert.ok(!fs.existsSync(path.join(root,'.agents-sync.lock')));});
test('duplicate JSON keys reject including escaped aliases and nested keys',t=>{const f=fixture(t);for(const input of ['{"harness":"codex","harness":"hermes"}','{"a":1,"\\u0061":2}','{"a":{"x":1,"x":2}}']){fs.writeFileSync(f.env,input);assert.throws(()=>f.sync(true),/duplicate JSON key/);assert.ok(!fs.existsSync(f.target));}assert.equal(ctl.parseJSON('{"__proto__":1}').__proto__,1);});
test('CLI committed cleanup warnings use stderr and return success',t=>{const f=fixture(t);f.sync(true);fs.writeFileSync(path.join(f.source,'SKILL.md'),'new');let stdout='',stderr='';const result=ctl.main(['sync','--env',f.env,'--repo',f.repo,'--apply'],{stdout:s=>stdout+=s,stderr:s=>stderr+=s,remove(p){if(path.basename(p).startsWith('.agents-backup-'))throw new Error('injected cleanup');ctl.remove(p);}});assert.equal(result,0);assert.equal(stdout,'update sample\n');assert.match(stderr,/warning:.*committed.*injected cleanup.*manual cleanup/);assert.deepEqual(f.sync(),['unchanged sample']);});
test('readRegular refuses symlinks and special files without following',t=>{assert.equal(typeof ctl.readRegular,'function');const f=fixture(t),link=path.join(f.source,'link');fs.symlinkSync(path.join(f.source,'SKILL.md'),link);assert.throws(()=>ctl.readRegular(link),ctl.SafetyError);fs.unlinkSync(link);assert.equal(spawnSync('mkfifo',[link]).status,0);assert.throws(()=>ctl.readRegular(link),ctl.SafetyError);});
test('unknown tilde user rejects',t=>{const f=fixture(t);f.environment.targets.skill='~unknown-user/skills';f.save();assert.throws(()=>f.sync(true),ctl.SafetyError);});
test('native markdown deploys to Claude and Cursor only',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.repo,'agent.md'),'# agent');Object.assign(f.catalog.items[0],{kind:'agent',path:'agent.md',name:'sample.md',harnesses:['claude','cursor']});f.environment.targets={agent:f.target};for(const h of ['claude','cursor']){f.environment.harness=h;f.save();assert.deepEqual(f.sync(true),[`${h==='claude'?'install':'unchanged'} sample`]);assert.equal(fs.readFileSync(path.join(f.target,'sample.md'),'utf8'),'# agent');}f.environment.harness='codex';f.save();assert.throws(()=>f.sync(true),/incompatible harness/);});
test('Cursor and Codex share idempotent skill ownership',t=>{const f=fixture(t);for(const h of ['cursor','codex']){f.environment.harness=h;f.save();assert.deepEqual(f.sync(true),[`${h==='cursor'?'install':'unchanged'} sample`]);}});
test('plugins copied without running executable scripts',t=>{const f=fixture(t),sentinel=path.join(f.base,'executed');fs.writeFileSync(path.join(f.source,'install.sh'),`#!/bin/sh\ntouch ${sentinel}\n`,{mode:0o755});f.catalog.items[0].kind='plugin';f.environment.targets={plugin:f.target};f.save();f.sync(true);assert.deepEqual(fs.readFileSync(path.join(f.source,'install.sh')),fs.readFileSync(path.join(f.target,'sample/install.sh')));assert.ok(!fs.existsSync(sentinel));});
test('CLI preview apply errors help version and strict ambiguous selection',t=>{assert.equal(typeof ctl.main,'function');const f=fixture(t),args=['sync','--env',f.env,'--repo',f.repo];let r=cli(args);assert.equal(r.status,0,r.stderr);assert.equal(r.stdout,'install sample\n');assert.ok(!fs.existsSync(f.target));r=cli([...args,'--apply']);assert.equal(r.status,0,r.stderr);assert.equal(cli(args).stdout,'unchanged sample\n');fs.writeFileSync(f.env,'{broken');r=cli([...args,'--apply']);assert.equal(r.status,2);assert.equal(r.stdout,'');assert.match(r.stderr,/error:/);assert.doesNotMatch(r.stderr,/Traceback| at /);for(const args of [['sync'],['sync','--harness','other'],['sync','--harness','cursor','--env',f.env],['sync','--env',f.env,'--wat'],['sync','--env',f.env,'--env',f.env]])assert.equal(cli(args).status,2);assert.match(cli(['--help']).stdout,/--harness/);assert.equal(cli(['--version']).stdout,'0.1.0\n');});
test('CLI surrogate configuration fields reject cleanly with no writes',t=>{const f=fixture(t),original=structuredClone(f.catalog),environment=structuredClone(f.environment);const mutators=[(c,e,s)=>e.targets.skill+=s,(c,e,s)=>c.items[0].path='skills/'+s,(c,e,s)=>c.items[0].id=s,(c,e,s)=>c.items[0].name=s,(c,e,s)=>e.items=[s],...['source','revision','license'].map(k=>(c,e,s)=>c.items[0].provenance[k]=s)];for(const s of ['\ud800','\udc80','\udfff'])for(const mutate of mutators){f.catalog=structuredClone(original);f.environment=structuredClone(environment);mutate(f.catalog,f.environment,s);f.save();const r=cli(['sync','--env',f.env,'--repo',f.repo,'--apply']);assert.equal(r.status,2,r.stderr);assert.equal(r.stdout,'');assert.match(r.stderr,/error:/);assert.doesNotMatch(r.stderr,/ at /);assert.ok(!fs.existsSync(f.target));}});
test('valid scalar Unicode source provenance and target accepted',t=>{const f=fixture(t),name='😀é';fs.renameSync(f.source,path.join(path.dirname(f.source),name));f.catalog.items[0].path='skills/'+name;f.catalog.items[0].provenance.source='https://example.test/'+name;f.environment.targets.skill=path.join(f.base,name);f.save();assert.deepEqual(f.sync(true),['install sample']);});
test('harness resolves bundled environment and home outside cwd without real profiles',t=>{const p=temp(t);const r=cli(['sync','--harness','cursor','--apply'],{cwd:p,env:{...process.env,HOME:p}});assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim().split('\n').length,37);assert.ok(fs.existsSync(path.join(p,'.agents/skills/ask-matt/SKILL.md')));const second=cli(['sync','--harness','codex','--apply'],{cwd:p,env:{...process.env,HOME:p}});assert.equal(second.status,0,second.stderr);assert.ok(second.stdout.trim().split('\n').every(s=>s.startsWith('unchanged ')));});
